// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMvl0sgcFsPzVg9HFGeHOjn-CS8_wbXLw',
    appId: '1:41971992776:web:de3fcaa8e47a1ce195fdfd',
    messagingSenderId: '41971992776',
    projectId: 'ddwork-d0d1b',
    authDomain: 'ddwork-d0d1b.firebaseapp.com',
    storageBucket: 'ddwork-d0d1b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC725zGIocwezOoTR3-81P__H-ab-z2ng',
    appId: '1:41971992776:android:80b44153890a74c895fdfd',
    messagingSenderId: '41971992776',
    projectId: 'ddwork-d0d1b',
    storageBucket: 'ddwork-d0d1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvwSxK3yvFwlJgKixRAmP6iZOxSR326iQ',
    appId: '1:41971992776:ios:1653e308d8bc6eb695fdfd',
    messagingSenderId: '41971992776',
    projectId: 'ddwork-d0d1b',
    storageBucket: 'ddwork-d0d1b.firebasestorage.app',
    iosClientId: '41971992776-r7m9cghe5u68s9madk16u6kjmv2acbb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.dd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMvl0sgcFsPzVg9HFGeHOjn-CS8_wbXLw',
    appId: '1:41971992776:web:2d3303bbdf9ec56495fdfd',
    messagingSenderId: '41971992776',
    projectId: 'ddwork-d0d1b',
    authDomain: 'ddwork-d0d1b.firebaseapp.com',
    storageBucket: 'ddwork-d0d1b.firebasestorage.app',
  );
}
